name: Convert Draw.io Files with Auto-ID

on:
  push:
    paths:
      - '**/*.drawio'
      - 'drawio_files/**'
  workflow_dispatch: # Enable manual triggering
    inputs:
      convert_all:
        description: 'Convert all diagrams (not just changed ones)'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

# Add concurrency control to prevent queued workflows and resolve XKEYBOARD issues
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.sha }}
  cancel-in-progress: false

# Add permissions needed for the workflow
permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history to detect changes
          
      # Step 2: Install dependencies
      - name: Install Draw.io and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb libgbm1 libnspr4 libnss3 libxss1 libasound2
          wget https://github.com/jgraph/drawio-desktop/releases/download/v26.2.2/drawio-amd64-26.2.2.deb
          sudo apt-get -f install -y
          sudo dpkg -i drawio-amd64-26.2.2.deb || sudo apt-get -f install -y
          
      # Step 3: Create output directories
      - name: Create output folders
        run: |
          mkdir -p svg_files html_files
          
          # Initialize CSV changelog with headers if it doesn't exist
          if [ ! -f "html_files/CHANGELOG.csv" ]; then
            echo "Date,Time,Diagram,Commit" > html_files/CHANGELOG.csv
          fi

      # Step 4: Find modified Draw.io files
      - name: Find modified Draw.io files
        id: changes
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.convert_all }}" == "true" ]]; then
            echo "Using all Draw.io files"
            find drawio_files -name "*.drawio" > /tmp/changed_files.txt
            echo "all_files=true" >> $GITHUB_OUTPUT
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "Finding changed Draw.io files"
            git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep "\.drawio$" > /tmp/changed_files.txt || true
            
            # Check if there are changes
            if [ -s /tmp/changed_files.txt ]; then
              echo "Changed Draw.io files found:"
              cat /tmp/changed_files.txt
              echo "all_files=false" >> $GITHUB_OUTPUT
              echo "has_changes=true" >> $GITHUB_OUTPUT
            else
              echo "No changed Draw.io files"
              echo "all_files=false" >> $GITHUB_OUTPUT
              echo "has_changes=false" >> $GITHUB_OUTPUT
            fi
          fi
          
      # Step 5: Convert .drawio files and assign auto IDs
      - name: Convert and Auto-assign IDs to Draw.io files
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          echo "Converting Draw.io files and adding auto-IDs..."
          # Make sure our scripts are executable
          chmod +x ./scripts/convert_and_auto_id.sh ./scripts/auto_id_converted_diagrams.sh
          
          # Run conversion with proper arguments
          if [[ "${{ steps.changes.outputs.all_files }}" == "true" ]]; then
            # Process all diagrams
            ./scripts/convert_and_auto_id.sh --all
          else
            # Process only changed diagrams
            ./scripts/convert_and_auto_id.sh --file-list /tmp/changed_files.txt
          fi
          
          # Our convert_and_auto_id.sh script handles all the conversion and ID assignment
          
      # Step 6: Commit and push changes
      - name: Commit and push changes
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          # Check if we have any changes to commit
          if git status --porcelain | grep -q .; then
            echo "Committing changes..."
                echo '<!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <title>'"$base"'</title>
            <style>
              body { margin: 0; padding: 0; }
              svg { max-width: 100%; height: auto; display: block; }
            git add svg_files/ html_files/ drawio_files/ 
            git commit -m "Auto convert and ID assignment for Draw.io diagrams [skip ci]" || echo "No changes to commit"
            git push
          else
            echo "No changes to commit"
          fi

# End of workflow - our files have been converted and committed
