name: Convert Drawio to HTML

on:
  push:
    paths:
      - '**/*.drawio'

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y fuse libfuse2 xvfb
          wget https://github.com/jgraph/drawio-desktop/releases/download/v21.6.8/drawio-amd64-21.6.8.deb
          sudo apt install -y ./drawio-amd64-21.6.8.deb

      - name: Create html_files directory
        run: mkdir -p html_files

      - name: Convert .drawio to HTML
        run: |
          for file in $(find . -name '*.drawio'); do
            filename=$(basename "$file")
            output_file="html_files/${filename%.drawio}.html"
            xvfb-run -a drawio -x -f html --crop -o "$output_file" "$file"
          done

      - name: Commit and push changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add html_files/*.html
          git commit -m "Auto-convert .drawio files to HTML" || echo "No changes to commit"
          git push
